package com.vincentmet.customquests.gui.editor;

public enum MenuSelection{
    CHAPTERS,
    CHAPTER,
    CHAPTER_TITLE,
    CHAPTER_TEXT,
    CHAPTER_QUESTLIST,
    QUESTS,
    QUEST,
    QUEST_BUTTON,
    QUEST_TITLE,
    QUEST_SUBTITLE,
    QUEST_TEXT,
    QUEST_DEPENDENCIES,
    QUEST_DEPENDENCIES_LIST,
    QUEST_TASKS,
    QUEST_TASK,
    QUEST_TASK_SUBTASKS,
    QUEST_TASK_SUBTASK,
    QUEST_REWARDS,
    QUEST_REWARD,
    QUEST_REWARD_SUBREWARDS,
    QUEST_REWARD_SUBREWARD,
    QUEST_POSITION
}